"""schema initial

Revision ID: 778c7129c41e
Revises: 
Create Date: 2026-09-11 12:44:30.454325
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '778c7129c41e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PREPROCESSING', 'TRANSCRIBING', 'AWAITING_VALIDATION', 'VALIDATED', 'INDEXED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='job_status'), nullable=False),
    sa.Column('arq_job_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_image_path', sa.String(length=1024), nullable=False),
    sa.Column('preprocessed_image_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_per_document')
    )
    op.create_index(op.f('ix_pages_document_id'), 'pages', ['document_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('origin', sa.Enum('OCR', 'HUMAN', name='transcription_origin'), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'revision', name='uq_revision_per_page')
    )
    op.create_index(op.f('ix_transcriptions_is_validated'), 'transcriptions', ['is_validated'], unique=False)
    op.create_index(op.f('ix_transcriptions_page_id'), 'transcriptions', ['page_id'], unique=False)
    op.create_table('confidence_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcription_id', sa.UUID(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_blocks_transcription_id'), 'confidence_blocks', ['transcription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confidence_blocks_transcription_id'), table_name='confidence_blocks')
    op.drop_table('confidence_blocks')
    op.drop_index(op.f('ix_transcriptions_page_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_is_validated'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_pages_document_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
